spring.application.name=com.CMS
spring.datasource.url=jdbc:mysql://localhost:3306/cms_db
spring.datasource.username=root
spring.datasource.password=Aniket@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true